Only declare Mark_Series_Only_Debug for actual debug builds
    ../src/core/m-gc.c:129:13: error: ‘void
    Mark_Series_Only_Debug(REBSER*)’ declared ‘static’ but never defined
    [-Werror=unused-function]
     static void Mark_Series_Only_Debug(REBSER *ser);
                 ^